name: React Build and Deploy

on:
  push:
    paths:
      - 'site/skater/**'
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '23'

    - name: Install Dependencies and Build
      run: |
        cd site/skater
        npm install
        npm run build

    - name: Zip up the build
      working-directory: ./site/skater
      run: tar -czf react_dist.tar.gz dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ./site/skater/react_dist.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
    - run: ls -R

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.WILL_EC2_HOST }}
        username: ${{ secrets.WILL_EC2_USER }}
        key: ${{ secrets.WILL_EC2_KEY }}
        source: "react_dist.tar.gz"
        target: "/home/ubuntu/skater/dist"

    - name: Execute remote command
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.WILL_EC2_HOST }}
        username: ${{ secrets.WILL_EC2_USER }}
        key: ${{ secrets.WILL_EC2_KEY }}
        script: |
          cd /home/ubuntu/skater/dist
          sudo rm -rf /var/www/html2
          sudo cp -r dist/* /var/www/html2
